"""initial schema: phases 1-4

Revision ID: 7cf5c8f678b7
Revises: 
Create Date: 2026-07-17 18:06:55.288058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf5c8f678b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)

    op.create_table('ledger_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('platform_cash', 'escrow_liability', 'provider_payable', 'fee_revenue', 'refund_payable', name='accounttype'), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'reference', name='uq_account_type_ref')
    )
    op.create_table('payout_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('senders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('senders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_senders_email'), ['email'], unique=True)

    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_event_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_event_id', name='uq_webhook_source_event')
    )
    op.create_table('provider_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_users_email'), ['email'], unique=True)

    op.create_table('service_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('price_cents > 0', name='ck_bundle_price_positive'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('face_value_cents', sa.Integer(), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('recipient_phone', sa.String(length=20), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('issued', 'redeemed', 'paid_out', 'expired', 'refunded', 'disputed', name='voucherstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('face_value_cents > 0', name='ck_voucher_value_positive'),
    sa.CheckConstraint('failed_attempts >= 0', name='ck_voucher_attempts_nonnegative'),
    sa.CheckConstraint('fee_cents >= 0', name='ck_voucher_fee_nonnegative'),
    sa.ForeignKeyConstraint(['bundle_id'], ['service_bundles.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vouchers_code_hash'), ['code_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_vouchers_recipient_phone'), ['recipient_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_vouchers_status'), ['status'], unique=False)

    op.create_table('callback_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'flagged', name='callbackstatus'), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_id')
    )
    with op.batch_alter_table('callback_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_callback_checks_status'), ['status'], unique=False)

    op.create_table('ledger_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('payout_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['payout_batches.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_id')
    )
    with op.batch_alter_table('payout_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_items_batch_id'), ['batch_id'], unique=False)

    op.create_table('purchase_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('recipient_phone', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'abandoned', name='intentstatus'), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['service_bundles.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_intents_public_id'), ['public_id'], unique=True)

    op.create_table('sms_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_phone', sa.String(length=20), nullable=False),
    sa.Column('body', sa.String(length=480), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'failed', name='smsstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gateway_message_id', sa.String(length=128), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_sms_attempts_nonnegative'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_messages_gateway_message_id'), ['gateway_message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sms_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_messages_to_phone'), ['to_phone'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents != 0', name='ck_entry_nonzero'),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_account_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('sms_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_messages_to_phone'))
        batch_op.drop_index(batch_op.f('ix_sms_messages_status'))
        batch_op.drop_index(batch_op.f('ix_sms_messages_gateway_message_id'))

    op.drop_table('sms_messages')
    with op.batch_alter_table('purchase_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_intents_public_id'))

    op.drop_table('purchase_intents')
    with op.batch_alter_table('payout_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_items_batch_id'))

    op.drop_table('payout_items')
    op.drop_table('ledger_transactions')
    with op.batch_alter_table('callback_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_callback_checks_status'))

    op.drop_table('callback_checks')
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vouchers_status'))
        batch_op.drop_index(batch_op.f('ix_vouchers_recipient_phone'))
        batch_op.drop_index(batch_op.f('ix_vouchers_code_hash'))

    op.drop_table('vouchers')
    op.drop_table('service_bundles')
    with op.batch_alter_table('provider_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_users_email'))

    op.drop_table('provider_users')
    op.drop_table('webhook_events')
    with op.batch_alter_table('senders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_senders_email'))

    op.drop_table('senders')
    op.drop_table('providers')
    op.drop_table('payout_batches')
    op.drop_table('ledger_accounts')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
